### PR TITLE
Adding tools dir and a simple script to analyse lending history

### PR DESCRIPTION
**Pull request by laxdog**
## Description
Simple analysis tool

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] **I have read CONTRIBUTING.md**
- [x] **I fully understand [Github Flow.](https://guides.github.com/introduction/flow/)**
- [x] **My code adheres to the [code style of this project.](https://poloniexlendingbot.readthedocs.io/en/latest/contributing.html)**
- [N/A] **I have updated the documentation in /docs if I have changed the config, arguments, logic in how the bot works, or anything that understandably needs a documentation change.**
- [N/A] **I have updated the config file accordingly if my change requires a new configuration setting or changes an existing one.**
- [N/A] **I have tested the bot with no issues for 24 continuous hours. If issues were experienced, they have been patched and tested again.**

### CODE REVIEW

**Comment by Evanito** [comment]
So this folder will hold scripts and the like?
Honestly seems out of scope of the regular bot.

**Comment by rnevet** [comment]
I'm working on this, thinking that it should be like a plug-in.

**Comment by laxdog** [comment]
@Evanito I mostly raised it to have the source for that little script here. 

The long term plan was to add to it and turn it into a module. 

The plugins idea is good. I think we discussed it before.

**Comment by utdrmac** [comment]
My $0.02, this should be a plugin and not a command-line tool. Those who are using the Docker version or running this as a cloud app won't be able to easily execute this. But if it was available as a 'tab' within the GUI to make an ajax-call, that would be better.

**Comment by rnevet** [comment]
@utdrmac this was the trigger for the AccountStats plugin.  This PR can be closed.

**Pull request closed without merging**
