### PR TITLE
printf is only available in sqlite3>=3.8.3

### PR DESCRIPTION
**Pull request by laxdog**
Using round makes it work on earlier versions

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] **I have read CONTRIBUTING.md**
- [x] **I fully understand [Github Flow.](https://guides.github.com/introduction/flow/)**
- [x] **My code adheres to the [code style of this project.](https://poloniexlendingbot.readthedocs.io/en/latest/contributing.html)**
- [N/A] **I have updated the documentation in /docs if I have changed the config, arguments, logic in how the bot works, or anything that understandably needs a documentation change.**
- [N/A] **I have updated the config file accordingly if my change requires a new configuration setting or changes an existing one.**
- [N/A] **I have tested the bot with no issues for 24 continuous hours. If issues were experienced, they have been patched and tested again.**

### CODE REVIEW

**Comment by laxdog** [comment]
@utdrmac

**Comment by utdrmac** [comment]
I was unaware that printf was a recent addition.

This is the difference I'm seeing. It might just be console display, I haven't tested code yet:

```
sqlite> SELECT strftime('%s', strftime('%Y-%m-%d 00:00:00', close)) ts, round(SUM(interest), 8) i FROM history WHERE currency = 'BTC' GROUP BY ts ORDER BY ts;
ts          i
----------  ----------
1502150400  4.415e-05
1502236800  0.00011898
1502323200  9.904e-05
1502409600  6.642e-05
1502496000  6.941e-05
1502582400  8.696e-05
1502668800  8.158e-05
1502755200  7.086e-05
1502841600  9.135e-05
1502928000  0.00013761
```

vs

```
sqlite> SELECT strftime('%s', strftime('%Y-%m-%d 00:00:00', close)) ts, printf('%.8f', SUM(interest)) i FROM history WHERE currency = 'BTC' GROUP BY ts ORDER BY ts;
ts          i
----------  ----------
1502150400  0.00004415
1502236800  0.00011898
1502323200  0.00009904
1502409600  0.00006642
1502496000  0.00006941
1502582400  0.00008696
1502668800  0.00008158
```

**Comment by utdrmac** [comment]
It's not going to work. The scientific notation gets returned to python as a string and gets stored as such in the JSON:

```
# cat www/history.json
{"ETH": [[1502150400, 2.082e-05, 2.082e-05],
```

**Comment by utdrmac** [comment]
Well, seems like google charts doesn't care.

**Comment by utdrmac** [comment]
am i allowed to push to this branch? I have some other chart-formatting improvements. make another PR?

**Comment by rnevet** [comment]
I think you'll anyway need to create a new PR as this one was merged, even if you push to the same branch.

**Comment by utdrmac** [comment]
Ha. Totally glazed over the fact it was merged already.

**Comment by laxdog** [comment]
I tested with this and it was fine.

**Pull request merged**
