### PR TITLE
Adjust AccountStats DB to support Bitfinex

### PR DESCRIPTION
**Pull request by rnevet**
Fix issue #478 duplicate entries on Bitfinex
Implement AccountStats upgrade
Upgrade AccounStatsDB to version 2

Set id and currency as unique keys for the database
This change erases the current DB and fetches it from the exchange

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] **I have read CONTRIBUTING.md**
- [x] **I fully understand [Github Flow.](https://guides.github.com/introduction/flow/)**
- [x] **My code adheres to the [code style of this project.](https://poloniexlendingbot.readthedocs.io/en/latest/contributing.html)**
- [N/A] **I have updated the documentation in /docs if I have changed the config, arguments, logic in how the bot works, or anything that understandably needs a documentation change.**
- [N/A] **I have updated the config file accordingly if my change requires a new configuration setting or changes an existing one.**
- [x] **I have tested the bot with no issues for 24 continuous hours. If issues were experienced, they have been patched and tested again.**

### CODE REVIEW

**Comment by rnevet** [comment]
@utdrmac Can you take a look?

**Comment by utdrmac** [comment]
Looks good. I downloaded this version of AccountStats.py and started up the bitfinex version of the bot. Seems the upgrade went good and it re-downloaded all of my history.

```
sqlite> PRAGMA user_version;
user_version
------------
2
```

**Comment by rnevet** [comment]
@utdrmac what do you think? merge?

**Comment by utdrmac** [comment]
Did you test the Polo side? I only tested Bitfinex side and it's good for me.

**Comment by rnevet** [comment]
Yes, been running this time on Poloniex and it looks good.

**Pull request merged**
