### PR TITLE
added a docker-compose file for simple docker runs

### PR DESCRIPTION
**Pull request by Foolre**
I saw the pull request about Docker made before. Though that way is considered a better practice it's efficient and modular, it requires more scripting and additions. I favor this way because i can teach it to my 5 year old brother.  Yes he doesn't know what Docker is.

## Description
this docker compose file mounts the source directory inside the container. So you can change your default.cfg locally, run docker-compose up and your bot is working. When you change your config, you'd do docker-compose down and docker-compose up again. 

I suggest this pull request because it makes it easy for people to deploy the bots and for developers to work in identical environments.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [N/A] **I have read CONTRIBUTING.md**
- [N/A] **I fully understand [Github Flow.](https://guides.github.com/introduction/flow/)**
- [N/A] **My code adheres to the [code style of this project.](https://poloniexlendingbot.readthedocs.io/en/latest/contributing.html)**
- [ ] **I have updated the documentation in /docs if I have changed the config, arguments, logic in how the bot works, or anything that understandably needs a documentation change.**
- [N/A] **I have updated the config file accordingly if my change requires a new configuration setting or changes an existing one.**
- [X] **I have tested the bot with no issues for 24 continuous hours. If issues were experienced, they have been patched and tested again.**

### CODE REVIEW

**Comment by laxdog** [comment]
This is definitely how I envisaged this working first time around. 

Testing now.

**Comment by Foolre** [comment]
@laxdog I just notice a bug. I'm sorry, the bot runs but because the volume gets mounted the libraries numpy and hypothesis aren't available. You can refuse this pull request, I will make it better.

**Comment by laxdog** [comment]
Still waiting on the image being downloaded, so np :)

Just update your forked repo and it'll update this PR.

**Comment by laxdog** [comment]
No need to close this

**Comment by rnevet** [comment]
@Foolre just commit the fix into the same branch, the PR will update itself.

**Comment by rnevet** [comment]
I'm not a docker user, how would you update the bot?

**Comment by Foolre** [comment]
@rnevet you would update it like you normally would and invoke a docker-compose down and docker-compose up -d.

In fact, the second you save the file on your disk the container has it too.

**Comment by laxdog** [comment]
Cool, did a pull, but I can't get on the page. Pretty sure it's my setup though as I can see that the port is being listened on with netstat. 

I'll have a closer look at it later when I have more time.

**Comment by rnevet** [comment]
Do we need documentation also?
https://github.com/BitBotFactory/poloniexlendingbot/blob/master/docs/installation.rst

**Comment by Evanito** [comment]
Yes, this will need an additional installation instructions section for installing into Docker.

**Comment by laxdog** [comment]
Looks good aside from the docs @Foolre , nice one :)

**Comment by rnevet** [comment]
Does this need docs or is it super straight forward?

**Comment by laxdog** [comment]
Technically both @rnevet . We could merge and I could do the docs I suppose.

**Comment by rnevet** [comment]
Fine from my side, I didn't test it as I need instructions ;)

**Pull request merged**
