### PR TITLE
Add Raw gap setting

### LINKED ISSUE #269: Feature request gapbottom and gaptop by nominal units count, not by % of the portfolio
gapbottom and gaptop variable are defined how far into the lending book (in percent of the balance for the respective coin) the bot will go

the % of the balance is not so relevant, as my balance can be changed from time to time, and as I think that the strategy of where to place my lending order has nothing to do with my personal balance.

I prefer to always place my order in depth of 60 to 80 btc inside the lending book, 1000 to 1200 eth inside the lending book, etc…

Can you please add variables which are similar to gapbottom and gaptop, but defined by nominal unit numbers, not % of the balance? That way, I don't need to change the config file every time I withdraw or deposit money to/from the lending account.

In the example I gave, If I want depth of 60-80 btc for lending bitcoin and depth of 1000-1200 eth for lending ether, I should config the suggested 

nominal_gapbottom 	= 60,
nominal_gaptop		= 80,

and 1000, 1200 in the eth respected coinconfig fields.

Of course, it is recommended to add boolean variable to define if the bot will use the % gapbottom, gaptop variables or the nomninal variable.

### PR DESCRIPTION
**Pull request by Evanito**
Allows users to set a hard value to skip in the lendbook, as opposed to only offering values relative to their balance.

Has a `gapmode` setting that allows switching between `relative`, `raw`,  or `rawbtc` gaps (and possibly even add a setting that is relative to the market's volume?)

Closes #269 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] **I have read CONTRIBUTING.md**
- [x] **I fully understand [Github Flow.](https://guides.github.com/introduction/flow/)**
- [x] **My code adheres to the [code style of this project.](https://poloniexlendingbot.readthedocs.io/en/latest/contributing.html)**
- [x] **I have updated the documentation in /docs if I have changed the config, arguments, logic in how the bot works, or anything that understandably needs a documentation change.**
- [x] **I have updated the config file accordingly if my change requires a new configuration setting or changes an existing one.**
- [x] **I have tested the bot with no issues for 24 continuous hours. If issues were experienced, they have been patched and tested again.**

### CODE REVIEW

**Comment by rnevet** [comment]
Would it make sense to have this option only in the specific coin config? it will then override the default behavior?

**Comment by Evanito** [comment]
I was thinking that this is a change for default behavior, but per-coin settings could be added later in the coincfg cleanup/removal/overhaul I was planning.

**Comment by rnevet** [comment]
I was actually thinking about making it simpler by having it only available as a specific coin config - not as a general config option.

**Comment by Evanito** [comment]
The same code is pointed at by both config types:

The default value is set by the general setting, which can be overwritten for specific coins. Everything after that is the same.

**Comment by Evanito** [comment]
Didn't want to do too much in one PR, coincfg cleanup is next.

**Pull request merged**
