### PR TITLE
Fixes issue with not having data because of caching

### LINKED ISSUE #447: KeyError: u'USD_BCH'
New Day...New Issues

My bot has been running fine on Bitfinex for 16 hours or so, and then today I had to close it to change a setting (gapbottom), and when I restart it I get -

2017-08-10 15:12:50 Error USD_BCH
Traceback (most recent call last):
  File "lendingbot.py", line 81, in <module>
    Lending.lend_all()
  File "/home/pi/Downloads/poloniexlendingbot-bit/modules/Lending.py", line 232, in lend_all
    usable_currencies += lend_cur(cur, total_lent, lending_balances, ticker)
  File "/home/pi/Downloads/poloniexlendingbot-bit/modules/Lending.py", line 429, in lend_cur
    raise msg
KeyError: u'USD_BCH'

Unhandled error, please open a Github issue so we can fix it!

Also tried changing gapbottom back to what it was before, to see if it was some weird bug, and itgives the same error with the setting back to how it was originally.

Any advice?

### PR DESCRIPTION
**Pull request by utdrmac**
Fixes #447 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] **I have read CONTRIBUTING.md**
- [x] **I fully understand [Github Flow.](https://guides.github.com/introduction/flow/)**
- [x] **My code adheres to the [code style of this project.](https://poloniexlendingbot.readthedocs.io/en/latest/contributing.html)**
- [x] **I have updated the documentation in /docs if I have changed the config, arguments, logic in how the bot works, or anything that understandably needs a documentation change.**
- [x] **I have updated the config file accordingly if my change requires a new configuration setting or changes an existing one.**
- [ ] **I have tested the bot with no issues for 24 continuous hours. If issues were experienced, they have been patched and tested again.**

### CODE REVIEW

**Comment by utdrmac** [comment]
Need to let this run for 24-48 hrs to be sure.

**Comment by utdrmac** [comment]
Yep. Was trying to find the most minimal way of fixing the issue. The first call by the Data.* function is what creates an empty cache cause it doesn't use any of that data. But the subsequent calls by lend_all(), if done within the next 60s, will receive the empty array and ticker won't contain the data. getTicker() uses usedCurrencies to do it's filtering.

**Comment by rnevet** [comment]
This wasn't happening on the Poloniex api as there is no cache there, I'm just wondering why the difference. @mahiso might be able to shed light.

**Comment by mahiso** [comment]
Poloniex API 'returnTicker" returns ticker of all pairs. There is no equivalent on Bitfinex to get all in one call, API have to call for each pair separately. Therefore the caching and filtering to reduce the needed calls.

**Comment by utdrmac** [comment]
@mahiso I read that too about their API. Sucks. They should change it to allow fetching all. It would reduce their own load as well cause people wouldn't have to make so many calls.

**Comment by mahiso** [comment]
@utdrmac: It is in v2: https://api.bitfinex.com/v2/tickers. But v2 is still beta. One other cool way could be the websocket interface (https://bitfinex.readme.io/v2/reference#ws-public-ticker). But I have not play with it until now.

**Comment by rnevet** [comment]
@utdrmac is this tested now?

**Comment by utdrmac** [comment]
I think I hit it again. Not sure if it was holdover from previous iteration or not. Let me keep on this.

**Pull request closed without merging**
