### PR TITLE
Bitfinex Api Improvements

### PR DESCRIPTION
**Pull request by mahiso**
PR contains:
- Rework of payload building and signing
- Ticker error handling
- Request rate error handling
- Some PEP-8 and pylints fixes

PR should solves:
- #447, #466, #471 : Exceptions will catched now and ticker retrieving continue whit next currency. No changing time when an error occurs or ticker list is empty.
- #484: Now conversion rates are shown for all currency with active lending positions.
- #490: I implemented not a limitation but now additional sleep time is added like with Poloniex.

PR makes following PRs obsolete:
- #463, #476

## TESTING STAGE
I tested it for more than 2 days without any issue. But please test it too esp. to catch rare issues, like the ticker problem.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] **I have read CONTRIBUTING.md**
- [x] **I fully understand [Github Flow.](https://guides.github.com/introduction/flow/)**
- [x] **My code adheres to the [code style of this project.](https://poloniexlendingbot.readthedocs.io/en/latest/contributing.html)**
- [ ] **I have updated the documentation in /docs if I have changed the config, arguments, logic in how the bot works, or anything that understandably needs a documentation change.**
- [ ] **I have updated the config file accordingly if my change requires a new configuration setting or changes an existing one.**
- [x] **I have tested the bot with no issues for 24 continuous hours. If issues were experienced, they have been patched and tested again.**

### CODE REVIEW

**Comment by rnevet** [comment]
Does this also solved the ticker issue? @mahiso @utdrmac

**Comment by utdrmac** [comment]
His PR seems very similar to one of my other fixes so it'll probably be fine. I will swap out my bitfinex code for this PR and give it a run.

**Comment by utdrmac** [comment]
Nope. Within 30 seconds:

```
[root@gasgiant bitfinex]# python lendingbot.py
Starting WebServer at 10.10.10.202 on port 8001 with template www
Welcome to Lending Bot on BITFINEX
Started WebServer, lendingbot status available at http://10.10.10.202:8001/lendingbot.html

2017-08-30 09:26:07 Error USD_ETH
Traceback (most recent call last):
  File "lendingbot.py", line 94, in <module>
    Lending.lend_all()
  File "/usr/src/bitfinex/modules/Lending.py", line 234, in lend_all
    usable_currencies += lend_cur(cur, total_lent, lending_balances, ticker)
  File "/usr/src/bitfinex/modules/Lending.py", line 431, in lend_cur
    raise msg
KeyError: u'USD_ETH'

Unhandled error, please open a Github issue so we can fix it!
```

**Comment by utdrmac** [comment]
The problem is here: https://github.com/mahiso/poloniexlendingbot/blob/ecdd54df156f0808634bcfc5f9f9e5186a54655a/modules/Bitfinex.py#L243

`self.return_ticker()` doesn't return what is needed and therefor the ticker array doesn't have all the information.

**Comment by utdrmac** [comment]
@mahiso #463 is still needed. Otherwise, on first run, self.usedCurrencies is empty and the for-symbols that follows doesn't add any ticker data to the array and then you get the missing key error above.

**Comment by utdrmac** [comment]
Hrm. Not sure why this is actually an issue. If you look at the main loop, it does this:

```
 Lending.transfer_balances()
 Lending.cancel_all()
 Lending.lend_all()
```

`transfer_balances` does call `api.return_available_account_balances` but for ('exchange') values. That's fine.

Next is `cancel_all()` which DOES call `api.return_available_account_balances('lending')` which SHOULD update `self.usedCurrencies` at this time but does not.

**Comment by utdrmac** [comment]
Hrm. Something is going out of order. `return_ticker` was called before `cancel_all`

**Comment by utdrmac** [comment]
`Data.update_conversion_rates` is the first thing called, which calls `ticker_response = api.return_ticker()` which as an empty `self.usedCurrencies` which returns an empty ticker (initially), but also caches the empty ticker for 60 seconds.

**Comment by utdrmac** [comment]
Two proposed solutions:

```
diff --git a/modules/Bitfinex.py b/modules/Bitfinex.py
index 6415b8b..b7b3332 100644
--- a/modules/Bitfinex.py
+++ b/modules/Bitfinex.py
@@ -133,6 +133,9 @@ class Bitfinex(ExchangeApi):

         setTickerTime = True

+        if len(self.usedCurrencies) == 0:
+            _ = self.return_available_account_balances("lending")
+
```

or

Move `Lending.cancel_all()` to fire before `Data.update_conversion_rates`

Either of those will cause usedCurrencies to be populated when return_tickers() is called.

**Comment by mahiso** [comment]
Now I have it... I had always set analyseCurrencies=ACTIVE. And this calls before the main loop return_available_account_balances

MarketAnalysis.init 
-> config.get_currencies_list()
-> ACTIVE -> Data.get_lending_currencies()
-> api.return_available_account_balances()

return_available_account_balances() is now called in api's __init__.

**Comment by utdrmac** [comment]
Thanks! re-pull'd PR. testing.

**Comment by utdrmac** [comment]
Looking good so far. Would be nice if it could gracefully handle some errors better:

```
Unhandled error, please open a Github issue so we can fix it!
2017-08-31 15:31:02 Error ('Connection aborted.', error(104, 'Connection reset by peer')) Requesting https://api.bitfinex.com/v1/credits
Traceback (most recent call last):
  File "lendingbot.py", line 90, in <module>
    Data.update_conversion_rates(output_currency, json_output_enabled)
  File "/usr/src/bitfinex/modules/Data.py", line 84, in update_conversion_rates
    total_lent = get_total_lent()[0]
  File "/usr/src/bitfinex/modules/Data.py", line 44, in get_total_lent
    crypto_lent = api.return_active_loans()
  File "/usr/src/bitfinex/modules/Bitfinex.py", line 122, in return_active_loans
    bfxResp = self._post('credits')
  File "/usr/src/bitfinex/modules/Bitfinex.py", line 78, in _post
    return self._request('post', payload['request'], signed_payload, verify)
  File "/usr/src/bitfinex/modules/Bitfinex.py", line 71, in _request
    raise ex
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
```

**Comment by rnevet** [comment]
@utdrmac could easily add a catch for all ConnectionError here:
https://github.com/BitBotFactory/poloniexlendingbot/blob/master/lendingbot.py#L104

**Comment by rnevet** [comment]
@mahiso any thing else before this is merged?

**Pull request merged**
