### PR TITLE
Bitfinex & Poloniex api impr

### PR DESCRIPTION
**Pull request by rnevet**
Introduce a 60 req per min limit to Bitfinex API
## Description
Introduce a 60 req per min limit to Bitfinex API
Fixed some minor python coding issues
Should fix issue #458
Improve Poloniex error messages

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] **I have read CONTRIBUTING.md**
- [X] **I fully understand [Github Flow.](https://guides.github.com/introduction/flow/)**
- [X] **My code adheres to the [code style of this project.](https://poloniexlendingbot.readthedocs.io/en/latest/contributing.html)**
- [N/A] **I have updated the documentation in /docs if I have changed the config, arguments, logic in how the bot works, or anything that understandably needs a documentation change.**
- [N/A] **I have updated the config file accordingly if my change requires a new configuration setting or changes an existing one.**
- [ ] **I have tested the bot with no issues for 24 continuous hours. If issues were experienced, they have been patched and tested again.**

### CODE REVIEW

**Comment by rnevet** [comment]
@mahiso @utdrmac I've wrote the 60 req / min limit, however didn't have a change to test it yet. Putting it here already for testing.

**Comment by laxdog** [comment]
Just found a problem. I haven't looked into it yet, but I think when it hits another error from bitfinex it ignores the ring buffer. I'll try to get a better test.

**Comment by mahiso** [comment]
Right, we need the limit.

But however, regarding MACD, 60req/sec will not be suffice. In  MarkedAnalysis/update_market_thread is a sleep of 5sec, but with only 5 currencies to analyse the 60 requests are hitted.

@laxdog Are you sure, that update_market_thread have to run as soon as possible? It will work on Poloniex well with his 6req/sec, but I believe not with Bitfiniex's 1req/sec.

**Comment by rnevet** [comment]
@laxdog @mahiso any objections to merging this branch?

**Comment by mahiso** [comment]
I have 6 currencies on lending and analyse it. The bot runs ok for 2..3 minutes, but then I get massive rates limit responses. Because marked analyses is not in main loop, the bot does not react (additional sleep) on rate limit errors.

**Comment by mahiso** [comment]
## Request: /v1/lendbook/IOT?limit_asks=10&limit_bids=10
Req: 1504449620  60th Req: 1504449550  Diff: 69.501368 sec
## Request: /v1/lendbook/EOS?limit_asks=10&limit_bids=10
Req: 1504449622  60th Req: 1504449550  Diff: 72.018304 sec
Error in returning data from Poloniex: API Error 429: { "error": "ERR_RATE_LIMIT"} Requesting https://api.bitfinex.com/v1/lendbook/EOS?limit_asks=10&limit_bids=10
Traceback (most recent call last):
  File "/home/maik/git/poloniexlendingbot/modules/MarketAnalysis.py", line 160, in update_market_thread
    raw_data = self.api.return_loan_orders(cur, levels)['offers']
  File "/home/maik/git/poloniexlendingbot/modules/Bitfinex.py", line 145, in return_loan_orders
    bfx_resp = self._get(command)
  File "/home/maik/git/poloniexlendingbot/modules/Bitfinex.py", line 115, in _get
    return self._request('get', request)
  File "/home/maik/git/poloniexlendingbot/modules/ExchangeApi.py", line 29, in new_method
    return method(self, *arg, **kws)
  File "/home/maik/git/poloniexlendingbot/modules/Bitfinex.py", line 104, in _request
    raise ex
ApiError: API Error 429: { "error": "ERR_RATE_LIMIT"}


Mmm, diff is >60sec, but received ERR_RATE_LIMIT... I incremented the sleep in update_market_thread to 10 and it runs fine with my 6 currencies.

**Comment by utdrmac** [comment]
Can this line be genericified in this PR since it's so small a change:

modules/MarketAnalysis.py#L162  - "Error in returning data from exchange."

**Comment by rnevet** [comment]
@utdrmac what would you like to have in those lines? (i'll add them)

**Comment by utdrmac** [comment]
Current HEAD still says 'Poloniex' and I think now they should just say 'exchange' (No need to put the actual name).

**Pull request merged**
