### PR TITLE
Trying to solve " local variable 'ticker' referenced before assignment"

### PR DESCRIPTION
**Pull request by Beppe1988**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] **I have read CONTRIBUTING.md**
- [ ] **I fully understand [Github Flow.](https://guides.github.com/introduction/flow/)**
- [ ] **My code adheres to the [code style of this project.](https://poloniexlendingbot.readthedocs.io/en/latest/contributing.html)**
- [ ] **I have updated the documentation in /docs if I have changed the config, arguments, logic in how the bot works, or anything that understandably needs a documentation change.**
- [ ] **I have updated the config file accordingly if my change requires a new configuration setting or changes an existing one.**
- [ ] **I have tested the bot with no issues for 24 continuous hours. If issues were experienced, they have been patched and tested again.**

### CODE REVIEW

**Comment by rnevet** [comment]
Is this tested? working?

**Comment by utdrmac** [comment]
A new error has appeared because of this fix. I'm attempting to solve both. @mahiso Needs to re-eval this whole ticker-return function.

**Comment by mahiso** [comment]
I will rework the method. Eta next week.

**Comment by utdrmac** [comment]
@mahiso @rnevet I'm [running with this code](http://termbin.com/bq0y) change for past 24hrs with no issues. All it does is "push" the code within the 'try' part of the exception. I think the issue with the original code is that all of that self.tickers code is outside the realm of the try/catch.

http://termbin.com/bq0y

**Comment by utdrmac** [comment]
@Beppe1988 How are things looking on your side? Did you try my code?

@rnevet @mahiso I've been running with this patch for almost a week. Haven't seen any issues.

**Comment by rnevet** [comment]
@utdrmac could you check the recent PR from @mahiso 
https://github.com/BitBotFactory/poloniexlendingbot/pull/499

**Comment by rnevet** [comment]
@utdrmac this is still needed, right?

**Comment by utdrmac** [comment]
I don't think so with the recent Bitfinex patch but I'll confirm when I get home.

**Comment by utdrmac** [comment]
@rnevet This is not needed any more. @mahiso 's recent patch seems to have fixed this.

**Comment by rnevet** [comment]
Thanks @utdrmac!

**Pull request closed without merging**
