### PR TITLE
Currency Whitelisting

### PR DESCRIPTION
**Pull request by mahiso**
NOT READY

Currency Whitelisting:

Bot will manage only currencies listed in "all_currencies" configuration attribute.

ToDos:
- Poloniex implementation
- Documentation

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] **I have read CONTRIBUTING.md**
- [x] **I fully understand [Github Flow.](https://guides.github.com/introduction/flow/)**
- [x] **My code adheres to the [code style of this project.](https://poloniexlendingbot.readthedocs.io/en/latest/contributing.html)**
- [ ] **I have updated the documentation in /docs if I have changed the config, arguments, logic in how the bot works, or anything that understandably needs a documentation change.**
- [ ] **I have updated the config file accordingly if my change requires a new configuration setting or changes an existing one.**
- [ ] **I have tested the bot with no issues for 24 continuous hours. If issues were experienced, they have been patched and tested again.**

### CODE REVIEW

**Comment by rnevet** [comment]
Isn't this a duplicate of #570?

**Comment by mahiso** [comment]
@rnevet: No, its not. #570 implemented a blacklisting, this PR is a whitelisting, so that the bot manage only currencies defined in all_currencies. So it is possible to lend by bot only a subset of currencies and others by hand. At now PR implements it for Bitfinex only, Poloniex will follow.

**Comment by rnevet** [comment]
@mahiso the whitelisting part is also included in the #570 implementation and as far as I can see for both platforms, no?

**Comment by rnevet** [comment]
Also I don't think this should be introduced on the API implementation level.

**Comment by mahiso** [comment]
The implementation at API level has the approach that it is not needed to care about it before every call. The API decides what currency (in all of calls and returns(!)) is allowed and which not.

**Comment by rnevet** [comment]
@mahiso #570 enforces whitelist for lending, which should be enough. Please review.

**Pull request closed without merging**
