### PR TITLE
Fix #402

### LINKED ISSUE #402: Error text too long ...
Hi

Today I had the error (see screenshot). I think you should add a maximum amount of characters since Poloniex return a complete website for this one.

unbenannt

### PR DESCRIPTION
**Pull request by mchl18**
Last commit fixes #402 for Bitfinex and also adds 526 to range.

## TESTING STAGE

Cannot test myself

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] **I have read CONTRIBUTING.md**
- [ ] **I fully understand [Github Flow.](https://guides.github.com/introduction/flow/)**
- [ ] **My code adheres to the [code style of this project.](https://poloniexlendingbot.readthedocs.io/en/latest/contributing.html)**
- [ ] **I have updated the documentation in /docs if I have changed the config, arguments, logic in how the bot works, or anything that understandably needs a documentation change.**
- [ ] **I have updated the config file accordingly if my change requires a new configuration setting or changes an existing one.**
- [ ] **I have tested the bot with no issues for 24 continuous hours. If issues were experienced, they have been patched and tested again.**

### CODE REVIEW

**Comment by rnevet** [comment]
@utdrmac can help with testing this? I still didn't setup bitfinex (personal reasons.)

**Comment by utdrmac** [comment]
@rnevet Yep. I've got the Bitfinex changes in play. Doing the 24hr test. Haven't seen that error show up again.

**Comment by mchl18** [comment]
Should the error message also be updated to tell that it is a cloudflare error?

**Comment by tisdall** [comment]
@mchl18 - The code is already not rendering the HTML...  The point to the code is to hide the huge Cloudflare HTML page since the API is _supposed_ to always respond with JSON.

**Comment by tisdall** [comment]
@mchl18 - sorry..  I just figured out you were asking @utdrmac for confirmation not questioning how it's supposed to work..  ^_^

**Comment by tisdall** [comment]
502 isn't necessarily Cloudflare...  I don't think it really matters what it says as there's nothing anyone can do about these errors.

**Comment by rnevet** [comment]
Looks good, merged.

**Pull request merged**
