### PR TITLE
prevents directory listing and redirects to lendingbot.html

### PR DESCRIPTION
**Pull request by mahiso**
Prevents directory listing and redirects to lendingbot.html.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] **I have read CONTRIBUTING.md**
- [x] **I fully understand [Github Flow.](https://guides.github.com/introduction/flow/)**
- [x] **My code adheres to the [code style of this project.](https://poloniexlendingbot.readthedocs.io/en/latest/contributing.html)**
- [ ] **I have updated the documentation in /docs if I have changed the config, arguments, logic in how the bot works, or anything that understandably needs a documentation change.**
- [ ] **I have updated the config file accordingly if my change requires a new configuration setting or changes an existing one.**
- [x] **I have tested the bot with no issues for 24 continuous hours. If issues were experienced, they have been patched and tested again.**

### CODE REVIEW

**Comment by tamaskan** [comment]
are you sure that not having a index.html-file is not intentional ?

**Comment by rnevet** [comment]
@tamaskan Sadly I don't remember why I decided not to add an index.html or to actually name the file index.html. Might have had an idea but can't think of one now.

**Comment by langerhans** [comment]
I'd suggest just renaming the lendingbot.html file to index.html. Given the very specific filename it is otherwise really easy to find running instances of the bot with a simple Google search. I also recommend adding a robots.txt to prevent crawlers from indexing the bot site regardless. The contents should be 
```
User-agent: *
Disallow: /
```
Otherwise there are still easy ways to find the bot.

**Comment by tamaskan** [comment]
there is only 1 reason i can imagine: you put the lendingbot.html beside your important index.html and upon a forced git pull the important index.html get replaced

**Comment by rnevet** [comment]
@tamaskan well this PR will create an index.html - which means that won't be possible anymore.
Ah! I remember, reason was I was running it locally (without a webserver), so I gave it a meaningful name.

**Comment by tamaskan** [comment]
mystery solved :-)

**Pull request merged**
